### ISSUE TITLE
Hook Prompt engine into some questions into the UI

### ISSUE THREAD

**Issue by BillyLuisNeedham** [BillyLuisNeedham/ai-helper#8]
## Todo
- [x] Use a GUIDE query
- [x] write test for page
- [x] Fix bug in how things display
- [x] Test
